struct stat;
struct rtcdate;

// system calls
void exit(int ) __attribute__((noreturn));
char* sbrk(int);
int fork(void);
int wait(int *);
int waitpid(int, int *, int);
int pipe(int*);
int write(int, void*, int);
int read(int, void*, int);
int close(int);
int kill(int);
int exec(char*, char**);
int open(char*, int);
int mknod(char*, short, short);
int unlink(char*);
int fstat(int fd, struct stat*);
int link(char*, char*);
int mkdir(char*);
int chdir(char*);
int dup(int);
int getpid(void);
int sleep(int);
int uptime(void);
int functPriority(int);
int* v2p(int, int*);
// ulib.c
int stat(char*, struct stat*);
int strcmp(const char*, const char*);
int atoi(const char*);
char* strcpy(char*, char*);
char* gets(char*, int max);
char* strchr(const char*, char);
void *memmove(void*, void*, int);
void printf(int, char*, ...);
void* memset(void*, int, uint);
void* malloc(uint);
void free(void*);
uint strlen(char*);
